var page = require('webpage').create(), system = require('system'), t, address;
  
page.onConsoleMessage = function (msg){
	console.log(msg);
};

page.onResourceError = function(resourceError) {
	page.reason = resourceError.errorString;
	page.reason_url = resourceError.url;
};

t = Date.now();
address = system.args[1];

try{
	page.open(address, function(status) {
		if (status !== 'success') {
			console.log("Error opening url \"" + page.reason_url + "\": " + page.reason);
			phantom.exit(1);
		} else {
			t = Date.now() - t;
			var data = page.content;
			console.log(data);
			console.log('<!-- Page properly generated by PhantomJS in ' + t + ' ms. -->');
			phantom.exit(0);
		}
	});
}
catch(e) {
	console.log(e.message);
}
